name: kafka-local
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.1.12
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
    ports:
      - "19092:19092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
volumes:
  redpanda-data:
